# This is what gets used in the "flasher" setting in a board configuration
tool_name = "avrdude"
tool_loc = ""

[tool_settings]
# Can be CLI or PYTHON
type = "cli"
# The supported board types. See board_type.py for available options
supported_boards = ["ARDUINO"]
# Supported file types
supported_file_types = ["*.hex", "*.bin"]
# CLI Arguments see the AVRDude implementation for more details
args = [
	"-c", "arduino",
	"-p", "$partid", 	# Variables can be used by prepending a $ to them, similar to powershell scripts
	"-P", "$port",		# See the how to use variables section in the readme for more info.
	"-b", "$baudrate",
	"-D",
	"-U", "flash:w:$file:i"
]