; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Flash Wizard"
; AppVersion is normally supplied on the command line (see `make installer`,
; which reads it out of pyproject.toml) via `ISCC /DAppVersion=x.y.z`, so the
; installer's version can't drift from the packaged app's. Falls back to a
; placeholder so the script still compiles standalone (e.g. opened directly
; in the Inno Setup IDE) without that define.
#ifndef AppVersion
  #define AppVersion "0.0.0-dev"
#endif
#define MyAppVersion AppVersion
#define MyAppPublisher "CookieJAR"
#define MyAppURL "https://flashwiz.cookiejar499.me"
#define MyAppExeName "upload_wiz.exe"
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4B50CA71-CDD5-4C76-B631-77A9ECF056A1}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={cm:NameAndVersion,{#EscapeConstArgument(MyAppName)},{#EscapeConstArgument(MyAppVersion)}}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\flashwiz
UsePreviousAppDir=yes
DisableDirPage=auto
UninstallDisplayIcon={app}\{#MyAppExeName}
SetupIconFile=..\assets\logo.ico
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
; This means it should use the native 64-bit Program Files directory and the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
; Uncomment the following line to use a 64-bit installer.
;SetupArchitecture=x64
DisableProgramGroupPage=yes
LicenseFile=..\LICENSE
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputDir=..\build
OutputBaseFilename=upload_wiz_setup
SolidCompression=yes
WizardStyle=modern dynamic
CloseApplications=yes
RestartApplications=yes
AppMutex=Global\FlashWizMutex

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "..\build\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent

